### ISSUE TITLE
deserializeUser so many times

### ISSUE THREAD

**Issue by ssmlee04** [linnovate/mean#1062]
I have rearranged the codes in the expressEngine.js and config/express.js so that the middleware orders are just like that in https://github.com/jaredhanson/passport/issues/14 now.  However by doing this my website still does 10-20 deserializeUser for one page load.

Also I have some routes that I wish to bypass deserializeUser because it's just a simple API that returns something.  So I wonder if this is possible? 

p.s: I believe deserializeUser 10x times is calling the db for 10x times. is there some way to cache the result?

also another question after I login to my website (using facebook login) I can see the page is rendered correctly.  But when I press F5 or go to other pages sometimes deserializeUser is not called and page is rendered as guest... Does anyone know what is happening?  Thanks.  (local strategy does not seem to have this problem)

**Comment by samhuntsocial** [comment]
As jaredhanson mentioned in [jaredhanson/passport/issues/83](https://github.com/jaredhanson/passport/issues/83#issuecomment-12340041), passport calls `deserializeUser` once *per request*. 

That means:
* x1 `.css` file is 1 request
* x2 `.js` files is 2 requests
* x5 `.jpg` file is 5 requests. 
Then there's other stuff too, like REST API (e.g. GET) calls via AJAX: 
* x3 'json' file is 3 requests  

That's already a total of 10 requests there. For some of my pages, I got a lot of tables and charts and each table and chart does a $.getJSON() so that's a lot of requests. 

If Passport hits the database on each request, that's a lot of hits. BUT, the way I did it was, I only hit the database in 3 scenarios: 
1) login (check if user exists in database, check if passport is valid, etc. for the user)
2) registration (add the user to the database) 
3) when user info changes (I'll know because it's not a GET request, but a POST, PUT, DELETE request)

**Comment by VikramTiwari** [comment]
@samhuntsocial @ssmlee04:
This seems like an awesome enhancement. I haven't done any perf testing myself, but love the insights. Could either of you take some time and review what we have on master right now and help us improve it? Thanks.
