### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.(http://xhr.spec.whatwg.org)

### ISSUE THREAD

**Issue by jcsena** [linnovate/mean#1071]
JQuery: Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

``` javascript
// ./node_modules/meanio/resources/web-bootstrap.js
jQuery.ajax('/_getModules', {
  dataType: 'json',
  async:true,
  success: processModules
});
```

http://stackoverflow.com/questions/24639335/javascript-console-log-causes-error-synchronous-xmlhttprequest-on-the-main-thr

tengo esta advertencia cuando se realiza esta peticion, estuve buscado la documentacion de esto.
Se puede cambiar la variable "async"?

thx!

**Comment by Jeff-Lewis** [comment]
+1000

**Comment by lvarayut** [comment]
I have the exact same issue. I tried to change `aysnc: true` which gave me some errors. Did you figure it out how to solve it?

**Comment by jsecademy** [comment]
All right I think I found a solution.

First of all the file that is causing this error is the following one.

```
bower_components/web-bootstrap/index.js
```

This file is not checked in to the main repository. Meaning that if you look for it you will not find it. This needs to be checked into the main branch for maintainability sakes.

Next we need a way to stop angular from requesting modules until all the modules have loaded into the page. Right now this is happening probably the worst way that it can by stoping the main thread and waiting.

What needs to happen is output that most static content on the page then wait for a promise to load all the modules then bootstrap angular after everything has loaded instead of blocking the main thread.

Just wanted to ask here if any one knows how to stop angular from calling modules until they exists?

**Comment by VikramTiwari** [comment]
This warning has been there since forever and I still see this on multiple projects, not just MEAN. Not sure if we should do something about this, or if this is in Angular's domain.
