### ISSUE TITLE
Node/NPM Compatibility Warnings when updating mean cli

### ISSUE THREAD

**Issue by hydrotik** [linnovate/mean#1076]
I did an update to Node/NPM before starting a new project with updating the mean-cli as well as initializing a new mean application. I got some warnings related to the expected node/npm version. Is this a concern?

**Comment by xelawafs** [comment]
I had the same problem on Ubuntu, I'm assuming you're using a Debian based kernel. Debian changed the nodejs package a while back to provide /usr/bin/***nodejs*** instead of /usr/bin/***node*** to avoid a collision with another package. That's why you get the warnings.

There's now a nodejs-legacy binary package containing /usr/bin/***node*** as a symlink to /usr/bin/***nodejs***. Installing it gets rid of the warning:
`sudo apt-get install nodejs-legacy`

At least that's what worked for me.

**Comment by VikramTiwari** [comment]
Fixed.
