### ISSUE TITLE
Heroku Deploy

### ISSUE THREAD

**Issue by mwizzle** [linnovate/mean#1155]
I just created a new mean.io project today and am able to start the app locally using 'gulp'. However, I get this error when trying to deploy to Heroku:

remote:        You're attempting to deploy mean without the mean-cli, the mean post install script traverses through all packages and takes care of their dependencies, please install mean-cli and continue...

I did run 'sudo npm install -g mean-cli'. Any suggestions would be appreciated...

**Comment by liorkesos** [comment]
We'll work on this on sunday.
Thanks for the report!
Lior

On Fri, May 1, 2015 at 8:46 AM, Mike Wang <notifications@github.com> wrote:

> I just created a new mean.io project today and can start the app using
> 'gulp'. However, I get this error when trying to deploy to Heroku:
>
> remote: You're attempting to deploy mean without the mean-cli, the mean
> post install script traverses through all packages and takes care of their
> dependencies, please install mean-cli and continue...
>
> I did run 'sudo npm install -g mean-cli'. Any suggestions would be
> appreciated...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1155>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by mwizzle** [comment]
Thanks for the quick response! Are you acknowledging this is a bug? Or just that you will investigate further on Sunday?

**Comment by liorkesos** [comment]
This is acknowledged as a bug which we understand it's origin...
meanio had a dependency for mean-cli and the only reason was because it ran
the mean-postinstall script which traverses in to your packages and runs
npm install bower install based on the packagejson and bower.json.
In one of the latest releases of meanio we removed the dependency to reduc
the install size (don't you hate those long npm installes??)
We thought we could assume that anybody deploying mean has mean-cli
installed but we focused on deployment on servers (like we use) and have
mislooked the cloud scenarios (totally our bad)
In any case if you could research on how to take the code from mean
postinstall and add it directly in to mean (probably in the /tools
directory under /scripts)
If someone forks and submits a PR I'll gladly merge.
best regards
Lior

On Fri, May 1, 2015 at 10:22 AM, Mike Wang <notifications@github.com> wrote:

> Thanks for the quick response! Are you acknowledging this is a bug? Or
> just that you will investigate further on Sunday?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1155#issuecomment-98064069>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by mwizzle** [comment]
Thanks for confirming!

**Comment by ravi0880** [comment]
Thanks for confirming. I am having the same issue when I deploy to Azure. Hope this gets resolved soon!

**Comment by ravi0880** [comment]
As a temporary solution, use earlier version of meanio at package.json and try to deploy..

package.json changes

`"postinstall": "node node_modules/meanio/node_modules/mean-cli/bin/mean-postinstall"`

`"meanio": "0.7.4"`

**Comment by mwizzle** [comment]
Thanks for the suggestion. Seems, deploy succeeds, but I run into this issue.

https://github.com/linnovate/mean/issues/1154

**Comment by mwizzle** [comment]
The Heroku deploy issue has been fixed for me by this commit:
https://github.com/linnovate/mean/commit/10ce2b7cc4222ce01bb4bc6778989055aba3c55b

Thank you!

**Comment by janpetras** [comment]
I still can't deploy to Heroku with gulp.

What buildstack do I use? Do I set to production? If I do, then gulp doesn't get installed. The deployment tutorial isn't relevant anymore, it's for grunt...

I get all this errors and impossible hang-ups such as... build stops because apparently, no 'require-dir' - although it's declared as a dependency.

Manually need to declare a gulp task in gulpfile.js.

I think you switched to gulp too fast. Deployment with grunt worked perfectly... I've been trying to deploy to Heroku for 2 days now, still no go.

**Comment by VikramTiwari** [comment]
@janpetras If this is still an issue with you, please reopen.
