### ISSUE TITLE
Installation of mean should not be done as root! bailing out

### ISSUE THREAD

**Issue by Longtete** [linnovate/mean#1158]
i'm running mean on SSH terminal why this always happen?

**Comment by Longtete** [comment]
i'm current on the /root to init my mean app

**Comment by liorkesos** [comment]
You should now t be running this as the 'root' user.
Create another user and install mean (with new users permissions).
Anything else is a security risk and leads to his and further frustration.

**Comment by tonyfader** [comment]
this is silly as mean's front-page says " sudo npm install -g mean-cli" which means for you to install globally with root-level permissions.

**Comment by liorkesos** [comment]
No it is not, 
The first cli command is root because We want to place the mean clibinary  in your system writeable path.
The rest of the application and it's running context  (wha happens when you run gulp) should not be root because any breach on it will award the attacker with root access to your machine.
If you look at bower you can see that the best practice is to avoid installing things as root because they cause a mix of permissions in your .npm and bower caches and cause problems later.
One part of being "oppinianted" is that we enforce the best practice we see (based on dozens support queries etc..)

**Comment by tonyfader** [comment]
Hi Lior, 

Thank you for your response and explanation, it was really helpful.  Very cool stuff!

**Comment by GitDoggo** [comment]
Why is [the doc](http://learn.mean.io/) saying : 

In linux install in globally as root
    `$ sudo npm install -g mean-cli`
    `$ mean init <myApp>`
    `$ cd <myApp> && npm install`

It's pretty confusing and misleading.
