### ISSUE TITLE
atom plugin

### ISSUE THREAD

**Issue by zwhitchcox** [linnovate/mean#1181]
So, first of all, thanks for merging my seo/routing changes! First time contributing to something like this, and that's awesome.

So onto my next trick haha...

This is kind of a crazy idea, but I think it could be awesome.

I'm sure you guys have heard of github's editor [atom.io](http://atom.io)

I was thinking maybe we could make a plugin for it...or maybe even a distro...anyway, the point is, mean could have its own app..

So, the app would have its own settings and everything. Opening the app would atomatically (no pun intended) start the server for the project you were on. We could add support for an ES6 version of the project, and everything could be managed through the app through menus and stuff like that. There is a whole realm of possibilities once we do this, and it could make getting off the ground way easier for new mean developers. It could also manage stuff like github and make the process of development a lot easier.

It wouldn't even have to be atom. We could use node-webkit or some such software and create a completely different app.

Anyway, if anyone has any interest, I can go ahead and get started developing it right away! And if the mean team wanted to create a repo that I could fork for the new project, that would be great too!

Anyway, thanks guys. Please let me know what you think.

**Comment by liorkesos** [comment]
First I'd like to thank you for your clean URL/so pr.
It is what of the most prominent steps forward in 0.5 and is great example
of how the community can drive development forward.
I think an atom based "meanstaller" (?) Is a great idea. It addresses the
biggest problem a newbie faces which is all of the requirements and a
lengthy 2-3 minute install process.
I can start imagining some more of the possibilities and challenges but
maybe it should be the wrapper for our "hello gitty" project - an
interactive mean instance serving as a tutorial...
Anyway this is very I ferreting and I'd love to get on a hangout with you
and possibly with brock (which is leading hellogitty) to discuss...
We have a long weekend here so I'll reach out at Monday...
Lior

**Comment by zwhitchcox** [comment]
Awesome that sounds good.

So, here are some things I was thinking the app could manage through a gui/wizards:

* terminal pages, and automatically start the app
* menu editor
* package/app installer
* page over writer (automatically generate new index pages overwriting the previous one)
* user admin page
* git controls
  * push to remote bare repository
* mongo editor page (open a terminal page to mongo)
* Possibly a preview page (i'm kind of on the fence about this, because I feel like people will want to use their own editors)


That's all I can think of right now, but I'm sure I'll add more on later, and if anyone else has anything, feel free to list those too!

**Comment by liorkesos** [comment]
Hi Zwithchcox (I did not find your  name? :) )
I added a few past and current  mean committers to the discussion because
it can really change what "mean" is and especially evolve the medium people
experience it.

To summarise your offer - have mean (either the default repo or some kind
of variant) be installed by downloading an atom.io/node-webkit standalone
installation with some features built in...

I really like the idea of an easier way to install mean especially helping
the windows crowd (which typically has more challanges in installing the
prerequisistes).

I like the idea of using this medium to deploy the hellogitty tutorial - we
can have the menu system to jump between the various lessons and make
everything simpler for newbies

I'd like to start and organize all of the ideas in the hellogitty namespace
because we have additional community effort there and I think this could
helo the work we're doing there as well...
We should probably use the hellogitty wiki
<https://github.com/linnovate/hellogitty/wiki/installer> to place some of
the ideas.
I'd also love to setup a hangout to discuss.

In the mean time starting a poc with a basic mean install and getting an
idea about the size, installation process seems like a great idea so lets
start playing with the medium.

I'm not sure if we need a seperate repo for this, lets start with a
subdirectry in hellogitty
<https://github.com/linnovate/hellogitty/tree/master/atom> as a prototype
and then decide if this is a generic mean attribute or a separate project.
I added you as a contributor to this so you can push freely to the repo..

I love the idea - lets see how it resonates with



On Sun, May 24, 2015 at 6:21 PM, zwhitchcox <notifications@github.com>
wrote:

> Awesome that sounds good.
>
> So, here are some things I was thinking the app could manage through a
> gui/wizards:
>
>    - terminal pages, and automatically start the app
>    - menu editor
>    - package/app installer
>    - page over writer (automatically generate new index pages overwriting
>    the previous one)
>    - user admin page
>    - git controls
>       - push to remote bare repository
>     - mongo editor page (open a terminal page to mongo)
>    - Possibly a preview page (i'm kind of on the fence about this,
>    because I feel like people will want to use their own editors)
>
> That's all I can think of right now, but I'm sure I'll add more on later,
> and if anyone else has anything, feel free to list those too!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1181#issuecomment-105026749>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by zwhitchcox** [comment]
@liorkesos Lior

I posted this in the gitter, but I'm not sure that you saw it, and I didn't think to @ you, so I'm reposting here:

Hey lior! I forgot to tell you, the name's Zane, btw 

But it's going all right. I actually wanted to ask your opinion on that. I've been reviewing the cloud 9 code (c9.io), and they've got a nice little project going on there. Everything works, and it's really easy to use and get up and running.

I was thinking of perhaps forking this repository to create a cloud based IDE. The main advantages this would offer are

* you could access your project from anywhere in the world
* you could also easily run the same program on your local machine (provided you have node, which you would need anyway)
* It would be relatively easy to translate this to a hosted solution provided by the linnovate team, creating a new source of revenue for the project

However, atom was originally created to be a cloud based IDE for github, but they ultimately abandoned this idea due to the lack of control being limited to a web browser. On the other hand, mean advantageously has a much narrower scope than atom and might naturally lend itself better to a cloud based solution. Do you have any thoughts on this?

**Comment by liorkesos** [comment]
Hey Zane,
I'd love to speak to you in skype/hangout
Send me your handle/s and we can brainstorm
Lior

On Thu, Jun 4, 2015 at 6:27 PM, zwhitchcox <notifications@github.com> wrote:

> @liorkesos <https://github.com/liorkesos> Lior
>
> I posted this in the gitter, but I'm not sure that you saw it, and I
> didn't think to @ you, so I'm reposting here:
>
> Hey lior! I forgot to tell you, the name's Zane, btw
>
> But it's going all right. I actually wanted to ask your opinion on that.
> I've been reviewing the cloud 9 code (c9.io), and they've got a nice
> little project going on there. Everything works, and it's really easy to
> use and get up and running.
>
> I was thinking of perhaps forking this repository to create a cloud based
> IDE. The main advantages this would offer are
>
>    - you could access your project from anywhere in the world
>    - you could also easily run the same program on your local machine
>    (provided you have node, which you would need anyway)
>    - It would be relatively easy to translate this to a hosted solution
>    provided by the linnovate team, creating a new source of revenue for the
>    project
>
> However, atom was originally created to be a cloud based IDE for github,
> but they ultimately abandoned this idea due to the lack of control being
> limited to a web browser. On the other hand, mean advantageously has a much
> narrower scope than atom and might naturally lend itself better to a cloud
> based solution. Do you have any thoughts on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1181#issuecomment-108935231>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by zwhitchcox** [comment]
Yes, that would be great. My gmail is just zwhitchcox [at] gmail [dot] com, can you call me from there?

I've got class until 3PM EST, that's 3 hours from now, but after that I'm free
