### ISSUE TITLE
mean and openshift

### ISSUE THREAD

**Issue by neilyc** [linnovate/mean#1188]
Hi,

It's been 2 days that I try to deploy my application on OpenShift without success.

Note that I did not use the openshift boilerplate but the mean stack from linnovate/mean because the boilerplate's mean version is pretty old !

Please, tell me that deploying this stack on OpenShift is possible ! : )

**Comment by liorkesos** [comment]
Can you update the latest mean@openshift to use the latest mean version?
Lior

**Comment by neilyc** [comment]
I Have no clue of how to do that (or i didn't understand !)

I tried to put "meanio": "latest", in the package.json but everything went wrong when launching node server.

**Comment by claustres** [comment]
I tried that as well a couple of monthes ago with no succes. Indeed, MEANIO tried to install bower/npm deps + mean packages in the "postinstall" phase. Because OpenShift does not have mean-cli pre-installed this did not work as expected because you do not have rights to install modules globally. You can try using a local installation of mean-cli & gulp. Now there is a separate script for the postinstall phase it might work better.

To perform additional tasks you can try to use action hooks instead. For information about action hooks, consult the documentation: http://openshift.github.io/documentation/oo_user_guide.html#action-hooks. Here is the one that I created at that time in .openshift/action_hooks/build (make it executable):
```
#!/usr/bin/env bash
# Save the old HOME so we can reset after script.
# bower and grunt both want
# to touch .local and .config files in $HOME which 
# isn't writeable on OSE.  So we set $HOME to 
# the REPO_DIR temporarily.
OLD_HOME=$HOME

cd $OPENSHIFT_REPO_DIR
export HOME=$OPENSHIFT_REPO_DIR
echo "INFO: HOME is now $HOME"

########## Does not work
#echo "INFO: Running 'mean-postinstall'"
#node node_modules/meanio/node_modules/mean-cli/bin/mean-postinstall

########## Work fine
echo "INFO: Running 'bower install'"
bower install

########## Does not work
#echo "INFO: Running 'grunt'"
#grunt

#########
export HOME=$OLD_HOME
echo "INFO: HOME is now $HOME"
```

Another option is to integrate everything in the repo. The main problem I have had is having no rights to write on the disk outside the repository and this caused some trouble...

**Comment by VikramTiwari** [comment]
Please reopen if still an issue.
