### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting

### ISSUE THREAD

**Issue by mmguide2003** [linnovate/mean#1191]
Following errors occurred :  

    packages/core/users/server/controllers/users.js:263
                        description: user.name + ' forgot his password.'
                                         ^
    TypeError: Cannot read property 'name' of undefined
        at .....packages/core/users/server/controllers/users.js:263:42
        at ..../node_modules/async/lib/async.js:544:30
        at .../packages/core/users/server/controllers/users.js:231:50
        at ..../node_modules/mongoose/lib/query.js:1173:16
         at...../node_modules/mongoose/node_modules/kareem/index.js:109:16
         at process._tickCallback (node.js:355:11)

**Comment by sasikumardr** [comment]
using  __req.body.text__  instead of __user.name__ will fix this problem

function(err, user) {

                var response = {
                    message: 'Mail successfully sent',
                    status: 'success'
                };

                if (err) {
                    response.message = 'User does not exist';
                    response.status = 'danger';

                    MeanUser.events.publish('forgotpassword', {
                        description: req.body.text + ' forgot his password.'
                    });
                }
                res.json(response);
            });

**Comment by codehacker7** [comment]
change this to  user.name + ' forgot his password.' 
as 
user["name"] + ' forgot his password.'

**Comment by VikramTiwari** [comment]
@mmguide2003 I guess you haven't updated from the core branch in a while. This issue was fixed months back as you can see from the commit https://github.com/linnovate/mean/commit/5e8a858344726e8a727909004266618e37bd2eeb and [file](https://github.com/linnovate/mean/blob/master/packages/core/users/server/controllers/users.js).

You can either pull changes from the core using https://github.com/linnovate/mean#staying-up-to-date or you can make the changes in your file as specified in the commit https://github.com/linnovate/mean/commit/5e8a858344726e8a727909004266618e37bd2eeb

Closing since already fixed. Reopen if you need more help.
