### ISSUE TITLE
Production enviroment - missing aggregated resources

### ISSUE THREAD

**Issue by vmartis** [linnovate/mean#1237]
GET /modules/aggregated.js 404
GET /modules/aggregated.css 404

Solution:
add configuration to to config\env\production.js file:
"aggregate: true"

**Comment by JulienBreux** [comment]
I'have the same problem.

#bug !

**Comment by sharphill** [comment]
Agree that it's a tricky bug! :)

And this is more like an inconsistency issue. 
Between:
//  aggregate: 'whatever that is not false, because boolean false value turns aggregation off', //false
And:
function findModulesDone (meanioinstance, app, defer) {
  var config = meanioinstance.config.clean;
  app.get('/_getModules',getModulesHandler.bind(null,meanioinstance));

  if(config.aggregate){
...

That's why solution vmartis via setting "aggregate: true" works.

To fix: Making "config.aggregate !== false", a.k.a, to be consistent with:
  Meanio.prototype.aggregatedsrc = function(ext, group, callback) {
    // Aggregated Data already exists and is ready
    if (Meanio.Singleton.config.clean.aggregate !== false){

**Comment by lvarayut** [comment]
Facing the same issue. Setting `aggregate: true` did the trick!

**Comment by thesir11** [comment]
Does making "aggregate: true" in configuration file leave any side effects? I've tested it and everything looks so far right now but I'm slightly afraid. Anyone faced any problems? Thanks.

**Comment by rjVapes** [comment]
This has been resolved in master, the issue was as @sharphill described.
