### ISSUE TITLE
A package can't specify specific environment config's

### ISSUE THREAD

**Issue by vtdave** [linnovate/mean#1238]
Although a package can set its own settings:
http://learn.mean.io/#mean-stack-packages-settings-object

that does not allow per-environment (dev / test / prod) settings.

these settings should live under:
/packages/custom/myPackage/server/config/env 

just like under config at the top level.

**Comment by BrockMcKean** [comment]
This is definitely something we need and should add, though I'm not sure exactly where. The actual full path of where the package's config ends up is irrelevant to me  as long as it ends up in the package. The suggested path name seems to be idiomatic and simple. 

However, it is important that we address what can and cannot be configured from inside a package as well as valid types for the configuration values. If we're passing objects and functions as configuration values, are there particular "types" we want to assume in `npm meanio` api implementations? 

Are these concerns relevant to address or not? Perhaps there are more? less?

**Comment by vtdave** [comment]
I feel like it's just an extension of the existing environmental configs.  I'd love if there was a little standardization put around it as far as location and format.

I feel like if there was a JS file who's name matched the running environment:
* development.js
* test.js
* production.js

which would specify key/value pairs for that environment, that would be good enough.

If you were concerned about clobbering important default values like hostname: etc, you could keep a dictionary of configs needed by core, basically make them reserved words (protected members) of the config.

99% of the time a package would just need to specify some configs it would use, for example in my aws package I have:
```
  aws: {
    access: {
      ABC123XYZ: {
        consumerName: 'who-is-using-the-aws-api',
        secretAccessKey: 'ASDFKJSLDKJFDSLKJFLDSKFJSDLKFJKDJSDLKJFSDLKJF'
      }
    }, 
    s3: {
      credentials: {
        accessKeyId: 'MY-ACCESS-KEY',
        secretAccessKey: 'MY-SECRET-ACCESS-KEY'
      },
      defaultRegion: 'us-west-2',
      defaultBucket: 'MY-BUCKET'
    },
    cloudfront: {
      url: 'https://subdomain.cloudfront.net',
      keypairId: 'MY-KEYPAIR-ID',
      privateKeyString: '-----BEGIN PRIVATE KEY-----ABC1234----END PRIVATE KEY----',
      privateKeyPath: 'packages/custom/aws/server/config/keys/my-PRIVATEKEY.pem'
    }
  }
```

This block changes based on environment, and if I publish this package, i need a way for people to set these values per env as well.

**Comment by BrockMcKean** [comment]
I would think that reading the contents of the directory and using the file names for envs is perfectly acceptable.

Additionally, I think that there does need to be some ways of still overriding external and core config very simply from within these config files. So, some api added to the core (node module meanio) that will support some callback formats to do special things if passed as a value to the core through the api to alter existing configs and enable reuse/dependency to the default value if it is important at all for the setting you want to change. 

Stateful configurations that have a function or object [of fn and var] could be used to, as stated achieve some sort of oop type `super` feature of the stack for configurations. Additionally, because you could pass it a function, array of functions, or an object, you could create some very interesting configurations. Maybe that's a little further down the road...
