### ISSUE TITLE
Example server routes don't work as suggested

### ISSUE THREAD

**Issue by rjVapes** [linnovate/mean#1299]
We've gotten a lot of confusion over the server routes that are generated automatically with packages.  Since JWT it's no longer possible to visit server routes that require authentication in the browser because there's no JWT Authorization happening.

I'd just like to determine if this is intended, or is a bug so we can work on it.  If it's intended, then we need to remove the links from the generated view so people aren't confused, and maybe replace it with an explanation or something.  If it's not intended, then it would be great if whoever worked on the JWT implementation could give some direction on fixing it.

**Comment by rjVapes** [comment]
I also figured I'd just put here the workaround for testing your routes with authorization via a REST client like Postman.

1) Log into your site, and get your JWT token from local storage
2) In your rest client, add a header of 'Authorization' with the value of 'Bearer [insert JWT Token]'
3) Make calls like normal

**Comment by BrockMcKean** [comment]
So, I think the problem with JWT is essentially there's only one state that triggers JWT authorization to be generated and everything else is dependent on that. Perhaps we should have some response and internal node log message that would explain that they must login to obtain JWT authentication and provide the option to turn it off in the browser in Development and simply redirect in Production.  The alternative would be to generate a JWT token at each REST endpoint if one is not received and treat that as an alternative global state that you would default to if you do not authenticate, and proceed naturally after that... but for a pure route test, with `curl` for example, there would be no easy way to help new people overcome JWT using that approach without turning it off. 

So, really I think this is just as much about taking a position that makes sense, documenting it, and building in some error messages so that people aren't scratching their heads when it doesn't work. Do any of the above proposed ideas sound reasonable or is there something else we could do? Anyone have a completely opposite view point and can explain why?

**Comment by rjVapes** [comment]
@BrockMcKean 
> So, I think the problem with JWT is essentially there's only one state that triggers JWT authorization to be generated and everything else is dependent on that.

What do you mean by this?  What state etc?

**Comment by claustres** [comment]
A nice link about that: http://stackoverflow.com/questions/24709944/jwt-token-in-postman-header
