### ISSUE TITLE
Redirected to '/' after a page refresh

### ISSUE THREAD

**Issue by dazwin** [linnovate/mean#1332]
Related to the fix for #1311, now after refreshing a page the user is redirected to '/'

Initial debugging shows that MeanUserKlass.onIdentity is being called with a response.token so the $location.url('/') branch is being executed.

**Comment by rjVapes** [comment]
Can you see if #1329 fixes the issue you're seeing?  Also is this related to local strategy only or are you seeing this with your twitter integration?

**Comment by dazwin** [comment]
So far so good (though I'd question coding style - !!( ... + 1) ?!).

Twitter login (for me, local strategy is disabled/de-styled for now so it's difficult to test).

**Comment by rjVapes** [comment]
hah, yeah I saw that too.  Also it should be using the new landing page config variable instead of '/' directly as the redirect.  I also have local strategy disabled and wasn't noticing the issue, so when I saw @emps fix I assumed it was something local I missed even though I test on a fresh mean.  Do you know what condition specifically causes it?  Maybe some stuff I do with route providers inhibits the issue for me.

**Comment by rjVapes** [comment]
@dazwin Can you verify that the fix by @emps solved this and close? :)

**Comment by dazwin** [comment]
I've been running these fixes for some time now - no issues.
