### ISSUE TITLE
Unclosed Issues

### ISSUE THREAD

**Issue by JrPribs** [linnovate/mean#1375]
Seeing lots of issues that have been corrected, but the issues are still open. I would be happy to clean up the issues but do not have permission to do so in the repo. Please provide sufficient access so I can clean up the issues (to improve contribution efforts), or have someone with access close all issues with merged code.

**Comment by VikramTiwari** [comment]
I know for a fact that @rjVapes is working on cleaning legacy issues. But if you find some issue that has been closed in some pull request, you should comment on that issue, while referencing the pull request that was the patch for it. That way it would be easier for us to confirm the fix and close down the issues.
As far as permissions are concerned, I would let @liorkesos address that.

**Comment by JrPribs** [comment]
@VikramTiwari Thanks! No problem, I don't need permissions now since there is a process for me to help identify those issues that could be closed.  @liorkesos I plan to continue to contribute, and if at sometime I prove to be "helpful" and am awarded some additional permissions than I wouldn't complain ;)

**Comment by liorkesos** [comment]
Jonathan, (and any one that wants to help clean up)
I'll give you a status that cam let you help with the cleanup
Whats your github id?
Lior

On Thu, Oct 29, 2015 at 7:53 AM, Jonathan Pribesh <notifications@github.com>
wrote:

> @VikramTiwari <https://github.com/VikramTiwari> Thanks! No problem, I
> don't need permissions now since there is a process for me to help identify
> those issues that could be closed. @liorkesos
> <https://github.com/liorkesos> I plan to continue to contribute, and if
> at sometime I prove to be "helpful" and am awarded some additional
> permissions than I wouldn't complain ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linnovate/mean/issues/1375#issuecomment-152083996>.
>



-- 

Lior Kesos - http://www.linnovate.net
Linnovate - Community Infrastructure Care
mail: lior@linnovate.net
office: +972 722500881
cell: +972 524305252
skype: liorkesos

**Comment by JrPribs** [comment]
@liorkesos Great, my github id is JrPribs The associated email is jpribes@wgu.edu. Thank you!

**Comment by rjVapes** [comment]
@JrPribs Thanks for the help.  I've been doing a few as I have time, and recently did a big sweep of PRs.  As you go through issues, any that you find that aren't solved, also please label them. ( @liorkesos can you just verify he'll have permission to apply labels? ).  That way once we're down to a managable number of issues we can start to prioritize bugs over feature requests, etc.

**Comment by JrPribs** [comment]
@rjVapes No problem! Yea, I have noticed a lack of labels on issues. I have no problem doing that. I've also noticed a lot of "stackoverflow" type questions, things that are not really repo issues. How are those handled once they are verified to be user or atleast not actual issues? Are they closed (pointing the user to stackoverflow or similar) or perhaps given a specific label?

**Comment by rjVapes** [comment]
There's a question label, and if it's still a relevant question and has an answer somewhere you can probably label it, and link the an issue or stack link and 'Close and comment'.  

In a perfect world all of the 'Questions' would be answered in our wiki or readme.  So that might mean we should have a 'Needs Documentation' label, which is converted to 'Question' once the proper documentation is created or the question becomes outdated.  We could still close them, but it would allow us a way to track what needs to be documented.

Linking related issues is something that would also be useful, as I know we have a handful of similar issues related to things like "User not authorized" etc.  But it'll be hard to handle that in a single pass without knowing the 200 other issues already.

I guess ultimately we should end up with 'Bugs' which we prioritize fixes for.  Feature requests which get reviewed at some point and either put on the roadmap or closed as 'wont fix' or whatever.  And questions, which we either answer, close and document, or end up spawning a bug or feature request from and link/close the question.

**Comment by JrPribs** [comment]
@rjVapes That sounds good to me. Once I have access to labels and closing comments and am able to go through some issues Im sure I'll have some more questions or suggestions. Ill try and document the process as we go along so we have a concise reference guide moving forward. Are there any contribution or issue submission guidelines? I don't see any in the wiki  (although I could be missing it).

**Comment by JrPribs** [comment]
@liorkesos Lmk when you are able to provide me with that access so I can help with issue clean up. Thanks!

**Comment by VikramTiwari** [comment]
I have closed a lot of issued today. Few points to be noted:

1. A lot of recent issues are creeping in cause of Node's version updates and dependency packages being slow in updating them.
2. There are a lot of enhancement requests that are pending.
3. Our documentations are very outdated and require a lot of cleanup and additions
4. We should add a guide for contributions. When any issue is opened, system info (NodeJS version, MEAN version etc) is required in all the cases.
