### ISSUE TITLE
Where did ng-app go?

### ISSUE THREAD

**Issue by rick4470** [linnovate/mean#1380]
I'm looking at the documentation for ui-router and they give an [example](https://github.com/angular-ui/ui-router) for a starter app. Is their a particular reason why ng-app is not being used with the default mean.io setup?

```html
<!doctype html>
<html ng-app="myApp">
<head>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.1.5/angular.min.js"></script>
    <script src="js/angular-ui-router.min.js"></script>
    <script>
        var myApp = angular.module('myApp', ['ui.router']);
        // For Component users, it should look like this:
        // var myApp = angular.module('myApp', [require('angular-ui-router')]);
    </script>
    ...
</head>
<body>
    ...
</body>
</html>
```

**Comment by claustres** [comment]
There is no *ng-app* in MEAN.io because the application is bootstrapped manually. This is required as the modules/packages are dynamically loaded on the client side based on the server configuration, so you don't know in advance which modules your app will depend on. The magic is done in the bower component called **web-bootstrap/index.js**.

An AJAX call (**/_getModules**) is first performed to retrieve the list of available modules on the server side, then each module is instanciated (with a name such as *mean.moduleName*) and at last, a Angular app called *mean* depending on all of these modules is bootstraped on the document root.
