### ISSUE TITLE
Failing on Gulp Startup

### ISSUE THREAD

**Issue by MK2018** [linnovate/mean#1395]
When I attempt to run the command "gulp" during the startup process of mean, per the documentation here: http://learn.mean.io/#mean-stack-installation-invoke-node-with-a-task-manager, it seems to get through the first few steps of the process, then fails. Here's a screenshot with the stack trace:

http://i.imgur.com/w9FbUhI.png

OS: Xubuntu 14.04
Mean status:

    MEAN VERSION: 0.5.5

    DB connection successful!

    MongoDB URI: mongodb://localhost/mean-dev

    checking meanio and global mean-cli versions
    mean-cli at latest version: 0.10.17
    meanio at latest version: 0.8.83
Node Version: v4.2.2
NPM Version: 2.14.7

I'm not quite sure exactly where the error is coming from, so any help is appreciated.
Thanks.

**Comment by rjVapes** [comment]
Try running `npm install` again.  Sometimes, due to the volume of dependencies, an intermittent connection problem can cause a package not to install.  It definitely looks like an npm install issue and it's missing a dependency that it should have.

You can also try with the latest npm if that doesn't seem to work.  I've recently installed on OSX with npm 3.4.0 and node 4.2.2 so know it works.

**Comment by MK2018** [comment]
I tried npm install and that didn't help, BUT once I updated my npm to 3.4.0, I had some more success.
For whatever reason, I had to run npm install twice after updating, but it works seamlessly now.
Thanks.

**Comment by rjVapes** [comment]
No problem.  It's just a ton of dependencies.  Sometimes I get a random failure over wireless due to connection etc.  I don't know if more recent versions have better failure handling or what.  Glad it's resolved :)
