### ISSUE TITLE
Gulp Production - bower_components/build 

### ISSUE THREAD

**Issue by n0nick2010** [linnovate/mean#1403]
hello,

i started the mean stack with "gulp production" on my production server and the gulp script create two files in the bower_components/build folder:

dist.min.css
dist.min.js

then i visited my mean application and only a aggregated.js and  aggregated.css  will be loaded.. 

i dont find any usage of "dist.min.css" and "dist.min.js" in the whole project....

why we creating a min file and dont use it? tested with the current mean version 0.5.5

in my production.js i removed the cssmin and uglify-tasks and it works fine..
so, the cssmin and uglify-tasks aren't no longer needed?

**Comment by rjVapes** [comment]
Production isn't meant to be run with gulp, at least not currently, so the gulp file is likely outdated.

**Comment by claustres** [comment]
Yes at the present time these files are generated but not used, the minification actually dynamically occurs on the server side. In my case I use these minified files for a phonegap app. I think it will be interesting if MEAN.io could generate all the minfied files, those for the dependencies (let say *dependencies.min.js*) and those for the web app source code (*let say application.min.js*), for all included modules. Indeed *dist.min.js* today is somewhat misleading because it is the minification of all dependencies in the global aggregation (*assets.json*), not the source code of your web app...

**Comment by VikramTiwari** [comment]
@claustres I am not sure if our versions differ, but the aggregated file contains the source code as well as dependencies. Though it would make sense to have them as separately minified files, should help in caching at-least aggregated dependencies.

**Comment by claustres** [comment]
Well I work on a customized v0.5.5, yes *aggregated.js* contains all but *dist.js* contains only the dependencies. Indeed, if you look at the gulp tasks for minification you will see it only relies on the **assets.json**.
