### ISSUE TITLE
show blank page after installing package

### ISSUE THREAD

**Issue by tingyn012** [linnovate/mean#1570]
So sorry for maybe asking a silly question, I am very new in web development and mean.io.

After I install mean.io, it can normally show pages in meanStarter, but when I installed packages,  go to localhost:3000 will show

GET / 304 - - 89.105 ms
GET /_getModules 304 - - 3.745 ms

> Uncaught Error: [$injector:nomod] Module 'mean.mean-admin' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
> 
> Uncaught Error: [$injector:modulerr] Failed to instantiate module mean due to:
> Error: [$injector:nomod] Module 'mean' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

get these errors in chrome F12 , hope someone can help me to solve this problem, thanks.

**Comment by rubenjimenez** [comment]
I'm suffering the same issue.

The main problem is that 'mean.mean-admin' is not created as an Angular module. AngularJS needs their modules to be created before using them.

https://docs.angularjs.org/api/ng/function/angular.module

Therefore you may solve the issue adding the module creation before your controller definition:

```
angular
    .module('mean.mean-admin', []);

  angular
    .module('mean.mean-admin')
    .controller('ControllerExample', ControllerExample);
```

You should also keep in mind that "mean-admin" is not a legal name for a package since JSHint doesn't allow scores in a var. Likely it will be the next error you face when you solve this one we're talking of.

What I cannot understand is how this error exists in an automatic scaffolding (mean package) from a production version, moreover this error didn't exist in previous MEAN versions.

Regards!

**Comment by timelf123** [comment]
This is a hack -- the `mean.mean-admin` module should be created by the meanio boostrap process. If you use this hack you will overwrite the module definition already in place `'ngClipboard', 'mean.users'`

Are you trying to inject the mean-admin package into your package? In that case, try `mean.admin` instead of `mean.mean-admin`

**Comment by snu-ceyda** [comment]
I had a similar problem while updating where my old custom packages weren't loading. If the packages you installed were created with an older version of mean then they maybe missing "mean.json".
Otherwise try using ""meanio-admin": "git://github.com/linnovate/meanio-admin.git#master"" in the package.json
