### ISSUE TITLE
Assets.json is not working or MEAN ignores it

### ISSUE THREAD

**Issue by rubenjimenez** [linnovate/mean#1587]
Hi,

After installing some packages via Bower I've added their JS files in the assets.json, but they are not taken or processed by MEAN. I had to link them in foot.html manually for being able to use them. I guess this is not the best way as the files are not minified or compressed within the /bundle/app.js with the rest of files.

The JS files inside bower_components are accesible through the browser so they are well installed and the route is correct.

What's wrong?

**Comment by manojchandrashekar** [comment]
Which version of meanio do you have?

The latest version ignores the assets.json file. I'm not even sure why that file still exists in the project.

**Comment by rubenjimenez** [comment]
Hi,

We're using 0.9.0 right now. In that case, where is it supposed to be the libraries routes we add to the project?

We're adding those routes to foot.html using <script> tags, but I guess this is not the best way as those files won't be aggregated with the rest in production.

**Comment by manojchandrashekar** [comment]
You have to use the 'import' statement. Check app.js in the root directory
for how it has been used.

Just a note - using import will inject all your JS files in their own
namespace because that's how webpack works. Meaning, if you have a "global"
variable declared in one JS file it will not be available in another
"imported" file.

On Aug 3, 2016 19:22, "Rubén Jiménez" <notifications@github.com> wrote:

Hi,

We're using 0.9.0 right now. In that case, where is it supposed to be the
libraries routes we add to the project?

We're adding those routes to foot.html using

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/linnovate/mean/issues/1587#issuecomment-237201102>, or mute
the thread
