### ISSUE TITLE
packages directory issue

### ISSUE THREAD

**Issue by rawanujoom** [linnovate/mean#1599]
I can see in older code version the packages folder used to be there and it contains views files, while on the current version of master there is no packages folder which leads to the assumption that it has to be auto generated. 
I have used mean CLI to init my app , and another time by cloning the repository, I keep reaching to the error of missing packages directory:

> ERROR in ./app.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ./packages

and when I manually `mkdir packages` in order to avoid the error, run` npm install` again, `npm cache clean` , `bower install`, `bower cache clean`, `gulp` , the packages folder remains empty though the gulp task paths in development.js file are reading from there , and the localhost:3000 keeps loading then times out.

> GET / - - - - ms

- it is also worth to mention that mangoose and sync packages had to be downloaded manually due to faced errors.

npm version 2.14.7
node version : v4.2.2 , and another time with v0.12.14 (using nvm).

**Comment by mjebbar17** [comment]
Same for me +1

**Comment by naydenovAnton** [comment]
Hell,

I think that your problem is that without a settings mean CLI is fetching code from MASTER branch.

Currently there is no such a directory ./packeges

I think this will be fix your problem: 

mean init <app-name> -b 0.6.0 - Will fetch 0.6.0 branch. Be sure that you have write permissions to main directory also because of meanStarter rename.

**Comment by matthesrieke** [comment]
I see the issue as well. Actually, this breaks the two line installation instruction on http://mean.io - this should be fixed.

**Comment by laddng** [comment]
This issue is happening to me as well. It brings in a lot of issues to the initial setup.

**Comment by obcidio** [comment]
Using the branch method, I was not able to get a stable instance up and running. Here's what I did to get a stable instance running:

1. Checkout the 0.6.0 branch and copied the packages directory to another location
2. Ran `mean init` as usual (no branch specification)
3. Copied the packages directory into the new directory created by the init script (be sure to rename the folder inside the packages directory to the name of your app when running init - default is `mean`, I used `myApp` - path should be something like `/packages/custom/myApp`)
4. Ran `npm install --verbose` (running it without verbose never produced a stable instance for some reason)

These steps produced a stable running instance

Also note, because of my server setup, I had to add a rule for the loopback interface in my iptables.

**Comment by thumarmahesh** [comment]
I think adding an empty packeges directory in the root should fix this.

**Comment by rawanujoom** [comment]
@obcidio Thank you! I followed your comment and it worked for me too . 
I also had to update my npm version to 3.10.2, but this should be fixed.

**Comment by rivkabenshalom** [comment]
fixed
