### ISSUE TITLE
Tokens are not supported by core modules

### ISSUE THREAD

**Issue by pun4drunk** [linnovate/mean#1639]
Take a look at attached screenshot

Unfortunately, Users module event don't provide support to tokenize button labels, therefore tokens + translate modules can't be used to provide i18n.

Am I the very first to notice this?

<img width="423" alt="i18n" src="https://cloud.githubusercontent.com/assets/4086559/17836334/26e67816-6797-11e6-9b83-2d402fe8942e.png">

**Comment by timelf123** [comment]
The tokens module has not been ported and is not compatible with latest mean (due to changes with the global system). It was never a "core" mean module so it hasn't gotten the love it probably deserves.

@liorkesos @ellman @linnovate/mean-contributors thoughts on moving the remaining git.mean.io packages over to github?

**Comment by VikramTiwari** [comment]
@timelf123 There are actually a lot of good packages there. Tokens, Uploads and Intercom being probably being the best ones. I will see if I can bring them over to GitHub this weekend.

**Comment by VikramTiwari** [comment]
Yet to do this. Moving this over to next milestone.
