### ISSUE TITLE
Task 'build' is not in your gulpfile

### ISSUE THREAD

**Issue by milad1367** [linnovate/mean#1658]
hi
I'm having trouble making Watch in Gallup.
this is my simple my gulpfile.js!
`var gulp = require('gulp');

gulp.task('watch', function () {
   gulp.watch('index.html', ['build']);
});`
and command error :
Task 'build' is not in your gulpfile

pls help

**Comment by VikramTiwari** [comment]
Not sure why are you writing your own GulpFile. Even then, you should read your code a bit before asking a question like that. `gulp.watch('index.html', ['build']);` line in your code is asking for a `build` step which is not defined anywhere in your file.
```
gulp.task('build', function () {
// your code
});
```
Adding this to your code will add the build step but you still need to write your process in there.

Closing since it's not relevant to MEAN.

**Comment by milad1367** [comment]
I know that by writing this task, problem solved! It is better not judge! I think I was wrong to engage a learning path. In no way do not like to spend my time and my futile questions.

**Comment by VikramTiwari** [comment]
It's not about you trying to learn. We want everyone to learn and actually discover issues that might be stuck on a lower level. For that, you are more than welcome to join us in Gitter and talk with others in the community. 

Issues are used to maintain the project, you can certainly ask questions around overall project arcitecture. But questions related to learning should be limited to Gitter (https://gitter.im/linnovate/mean).
