### ISSUE TITLE
Windows version of mean.io expects mv command

### ISSUE THREAD

**Issue by Matthew22877288287** [linnovate/mean#1817]
I get this error when installing my app using the mean command:
'mv' is not recognized as an internal or external command, operable program or batch file.

I can't find mv executable in Windows. Is there one?

**Comment by rogeriob2br** [comment]
Hi, please try to provide more details, such as:
"Windows Version"
"Mean Version"

> 'mv' is a **Powershell command** to move item or directory, command prompt does not recognize this command.

![image](https://user-images.githubusercontent.com/25432584/28047511-e5543ffe-65c0-11e7-83b2-b599e1240b4e.png)

**Comment by rogeriob2br** [comment]
I usually clone the project master for new apps. Is it correct?

**Comment by Matthew22877288287** [comment]
Windows 8.1
Mean: 0.12.15

Thanks for the reply. :)

**Comment by Matthew22877288287** [comment]
I changed install.js for shell.exec('mv ') to shell.exec('move '
and I get a new message:
  Added the "remote" upstream origin
  The system cannot find the path specified.

**Comment by Matthew22877288287** [comment]
I tried in Powershell and still get error with code 'mv ' instead of 'move '.

**Comment by rogeriob2br** [comment]
Sorry, can you post the code you changed for better understanding?

**Comment by rogeriob2br** [comment]
The first Line is a confirmation for git command. (Line 284 in install.js)
The Second Line is an error for de renname command in linux. This error seems to be because of the package path. 
This path "/packages/custom/meanStarter" exists in 1.x branch of Mean.io Project, but not exists in Master Branch, and the git clone command in mean-cli point to Master Branch.

This is a Bug of Mean-cli, and i believe that i can open a PR to fix this.

**Comment by rogeriob2br** [comment]
You can remove the rename function for a  workaround.

**Comment by Matthew22877288287** [comment]
I removed the rename function. Now 'bower install' won't work. Please help.
