### ISSUE TITLE
Multiple Angular errors when executing build/run

### ISSUE THREAD

**Issue by msturge** [linnovate/mean#1850]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
When running the commands listed on the main page:
$ git clone https://github.com/linnovate/mean.git
 $ cd mean
 $ npm install && npm start

The build completes with multiple errors, many of them relating to Angular.

[nodestart.txt](https://github.com/linnovate/mean/files/1435273/nodestart.txt) shows full text from attempting to start server with the command "npm start"

I have also attached a screenshot of the loaded page on localhost:3000

![screenshot from 2017-11-01 16-01-47](https://user-images.githubusercontent.com/11647855/32291174-4017adba-bf1f-11e7-89cc-c3017dee8701.png)

* **What is the expected behavior?**
Clone, npm install dependencies , npm start server and display running site.

* **Please tell us about your environment:**
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
 I am currently running Node.js v7.10.1

Browser Chrome Version 60.0.3112.78 (Official Build) (64-bit)

**Comment by chanakaDe** [comment]
@msturge Hey buddy,
I can see a "BLOCKED BY CLIENT" issue. It's not regarding to the application and also it's not series issue. But the angular material issue : it's because the version is deprecated. You have to downgrade it.
Please check this link and then you will get an understanding.
https://stackoverflow.com/questions/46628211/export-materialmodule-was-not-found-in-angular-material

**Comment by matsum0623** [comment]
fixed those bugs with pull request #1846.
