### ISSUE TITLE
getting MockMatchMedia error

### ISSUE THREAD

**Issue by Nehadigi** [linnovate/mean#1925]
After npm start getting this "ERROR in src/app/shared/shared.module.ts(4,34): error TS2307: Cannot find module '@angular/flex-layout'"
and when install @angular/flex-layout then getting this error.

ERROR in node_modules/@angular/flex-layout/core/typings/match-media/mock/mock-match-media.d.ts(25,15): error TS2416: Property '_registry' in type 'MockMatchMedia' is not assignable to the same property in base type 'MatchMedia'.

**Comment by duongtranfu** [comment]
Same issue here

**Comment by ArmandBahi** [comment]
Same issue too

**Comment by koelle25** [comment]
I get a similar error when using the docker method:
```
ERROR in app/shared/shared.module.ts(48,5): Error during template compile of 'SharedModule'
  Could not resolve @angular/flex-layout relative to /usr/src/app/src/app/shared/shared.module.ts..
src/app/shared/shared.module.ts(4,34): error TS2307: Cannot find module '@angular/flex-layout'.
```

Adding `"@angular/flex-layout": "^6.0.0-beta.18"` to _package.json_ seems to fix it.

**Comment by yogesh2022** [comment]
This issue is because of webpack... Steps I took to fix this problem:

Package.json: remove webpack from Dependencies
rm -R node_modules (remove node_modules folder)
npm i -g webpack
npm i -g webpack-dev-server
remove package-lock.json (if it's there)
npm i
npm start

Also for @angular/flex-layout', you can comment that code and try rebuilding the app.
