### ISSUE TITLE
authentication client side: no window.user after login until page refresh

### ISSUE THREAD

**Issue by w3bappd3v** [linnovate/mean#454]
log in or logout then login

after submitting new article taken to the article id page - no edit or delete icons

or if there are articles in the db click on article from list articles

the edit and delete icons flash and dissappear

refresh page and they show normal for remainder of session

edit: this is because ng-show in view.html evals to false because global.user._id is undefined

ultimately undefined because of following comment about window.user = {{user|json|safe}}

**Comment by MushroomData** [comment]
Hello, I'm also very new to mean.io and don't know the rules/etiquette for contributing. 

Anyway, I've reproduced this problem using version 0.4.3 and can see that $rootScope.$emit('loggedin') used throughout /users/public successfully dispatches the "loggedin" event up the hierarchy notifying dependent packages when the scope.global.user is updated.  

The issue seems to start in the HeaderController using $rootScope.$on("loggedin") to update $scope.global.user. Unfortunately the HeaderController declares a new $scope.global scope causing the global factory not to dispatch changes to other packages. 

WORKAROUND: For my project I hacked the LoginCtrl to use window.location.reload() which forces the global factory to dispatch changes to HeaderCtrl.

Note>>> This is why the admin role works. Mean will force a window.location.reload() if the admin role exists to update the home view with admin bar.

POTENTIAL FIX: Move the $rootScope.$on("loggedin") to the global factory, any thoughts?

Hope this helps.
