### ISSUE TITLE
menus not working in Internet Explorer

### ISSUE THREAD

**Issue by pasket** [linnovate/mean#620]
1. Install and start mean
  $ sudo npm install -g meanio 
  $ mean init yourNewApp
  $ cd yourNewApp&& npm install
  $ grunt

2. Navigate to localhost:3000 with Chrome 
    - Create a user and you can access to articles menu.

3. Do the same with Internet Explorer
    - Articles menu is not shown.

**Comment by chrsch** [comment]
I think this issue should be reopened. Experiencing the same behavior on IE 11. This should be considered a serious issue, many big companies stick with IE 11 and will do so for quiet some years probably (though this is bad luck for any web app technology).

With the IE tools open (F12) everything works. After closing the tools the login/logout is not processed correctly. Only restart of IE 11  will bring back correct app behavior.

I too think it is all about some caching in IE - but I don't have a clue where to look. Will investigate though and any pointers are welcome..

**Comment by davecyen** [comment]
@liorkesos agree w/ @chrsch that this should be re-opened. We've had several users contact us regarding this issue.

**Comment by mwizzle** [comment]
@chrsch We encountered this problem as well on IE. The problem is that IE caches the menu items.

IE's caching behavior was causing problems on other parts of our site as well, so I decided to disable caching by default and added the Cache-Control and Pragma headers to $httpProvider.

i.e.
    $httpProvider.defaults.headers.get['Cache-Control'] = 'no-cache';
    $httpProvider.defaults.headers.get.Pragma = 'no-cache';

@liorkesos, not sure if this is the right solution for the general mean.io user.
