### ISSUE TITLE
Bootstrapping apps with just a few layers

### ISSUE THREAD

**Issue by marcellodesales** [linnovate/mean#819]
Hi there,

I'm curious to know if there are "mean init" switches that allows me to only choose which layers I will have enabled... For instance, when creating a simple RESTFul service with just routes, I would only have the "E", or just have loaded the Express component. That avoids problems like the following:

```
Error: failed to connect to [localhost:27017]
**Could not connect to MongoDB. Please ensure mongod is running and restart MEAN app.**
```

Since the init command provides the full support, here' what I'm looking for:

```
$ mean init my-service --less-M --less-A
```

This would give me all the server without "MongoDB" and "Angular". Transitively, I would not also have the "public" folder... Since E and N are essential components of the framework, there would be no option for those :dart: All the other components would be added, from the MVC pieces, API, etc.

My requirement is to provide support for creating stateless services at start. Then, users would be able to add the other "letters" as they evolve their application. 

```
# mean update --plus-M
```

This would add the MongoDB module and its dependencies and generate any necessary boilerplate to hook the application state to the database. 

thanks
Marcello

**Comment by VikramTiwari** [comment]
@marcellodesales There are amazing templating projects that are around individual parts of MEAN stack. Since MEAN is a full stack project, it comes with some tight integrations with each other part which are not so easy to take apart and require significant effort.

I would be totally up for that effort if there wasn't something better out already. But I find amazing getting-started projects for angular and express both with many other databases. Express generator should be perfect for you. http://expressjs.com/en/starter/generator.html
