### ISSUE TITLE
html2js for templates/views

### ISSUE THREAD

**Issue by hydrotik** [linnovate/mean#965]
Any plans to include html2js for templates/views?

**Comment by hydrotik** [comment]
Is there a recommended way to implement this until it is part of core?

**Comment by VikramTiwari** [comment]
Not sure if there are any plans for this but since it's not been worked upon since 2014 I would assume that there isn't much support around it. If you would like it to be re-reviewed by the team, feel free to re-open.

Also, team is gearing up to work on MEAN2.0 with angular 2.0 which means that this will be implemented in one way or another.
